#! /bin/sh

xrdb ~/.Xresources

RED=$(xrdb -query | grep 'color9:'| awk '{print $NF}')

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border colors
bspc config normal_border_color "#000000"
bspc config focused_border_color "$RED"

bspc config focus_follows_pointer true

bspc rule -a Firefox desktop='^2'

sxhkd &
devmon &

feh --bg-fill ~/Pictures/wallpapers/sombra.png

~/.config/polybar/launch.sh

xsetroot -cursor_name left_ptr

xmodmap ~/.config/.Xmodmap
